Feature/staking page
White-Whale-Defi-Platform/white-whale-frontend pull request #172
Opened 2023-02-22 18:28 UTC by worrex

Added staking page with placeholder values for price, total amount staked and several other values

Fixed some typos

## Related Issues

---

## Checklist:

- [ ] I have read [Migaloo's contribution guidelines](https://github.com/White-Whale-Defi-Platform/migaloo-frontend/blob/main/CONTRIBUTING.md).
- [ ] My pull request has a sound title and description (not something vague like `Update index.md`)
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation.
- [ ] The code is formatted properly `yarn lint`.
- [ ] The project builds and is able to deploy on Netlify `yarn build`.

2023-03-06 18:07 UTC, Sen-Com commented
Hit the linked issue limit. #192 is also relevant

2023-03-07 11:06 UTC, Sen-Com commented
Added #195

2023-03-30 09:55 UTC, 0xFable approved these changes
Took quite a while to review the whole thing but think thats because of diff from terra station and new pools being in here. 
Overall looking very good! Most of the contract related stuff like queries and actions looks nicely isolated into their own Hooks. 
Pls add more comments on the lets say more cryptic or longer parts of code. Some of it looks very concise but some explanations will help other devs and the public

2023-03-30 09:55 UTC, 0xFable commented on components/Pages/Swap/hooks/useTransaction.tsx
> +                                 enabled,
This formatting looks a little off, do you have like 8 tabs as your setting ? Maybe fine

2023-03-30 09:55 UTC, 0xFable commented on components/Pages/Dashboard/hooks/useUnbonding.ts
> +  const unbondingAmpWhale = convertMicroDenomToDenom(filteredAmpWhaleUnbondingRequests?.map(req => req.asset.amount).reduce((accumulator: number, currentValue: string) => {
nice bit of map reduce, kudos

2023-03-30 09:55 UTC, 0xFable commented on components/Pages/Dashboard/hooks/useCurrentEpoch.ts
> +export const useCurrentEpoch = (client: Wallet | null) => {
I like how you be splitting the queries into different hooks. Maybe if we get loads of different types of hooks we could segregate it even more. But this looks great

2023-03-30 09:55 UTC, 0xFable commented on components/Pages/BondingActions/hooks/useTransaction.tsx
> +                return "Dashboard Failed.";
Bonding failed maybe

2023-03-30 09:55 UTC, 0xFable commented on components/Pages/BondingActions/hooks/useTransaction.tsx
> +                return "Dashboard Successful.";
same?

2023-04-17 11:01 UTC, 0xFable requested changes
Changes looking very good ! Pls add some comments and rename a few things for maintainability but otherwise LGTM! Would like to do some internal testing on this.

2023-04-17 11:01 UTC, 0xFable commented on components/Pages/Dashboard/hooks/getUnbonding.ts
> +  const unbondingPeriod = 60 * 1_000_000_000;
make both constants

2023-04-19 15:11 UTC, worrex commented on components/Pages/Dashboard/hooks/useWithdrawable.ts
> +    withdrawable: {address: address, denom: B_WHALE_DENOM},
we do not have these tokens in the testnet and so no corresponding addresses, its just a placeholder

2023-04-27 16:29 UTC, Sen-Com approved these changes

2023-04-27 16:32 UTC, merged